In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [17]:
df = pd.read_pickle(r'C:\Users\mpaks\Downloads\gBR_sBM_cAll_d04_mBR0_ch01.pkl')

In [18]:
print(df)

{'smpl_loss': 1.5907235145568848, 'smpl_poses': array([[-0.31962776,  0.06308482, -0.10600757, ..., -0.00279232,
         0.00125968,  0.00673836],
       [-0.31940448,  0.06222648, -0.10417131, ..., -0.00263791,
         0.00105115,  0.00658031],
       [-0.31785855,  0.05951827, -0.10288486, ..., -0.00242662,
         0.00085484,  0.00638444],
       ...,
       [-0.02737845,  0.5998614 ,  0.02344459, ...,  0.00208174,
         0.00185507,  0.01033406],
       [-0.02597483,  0.5952404 ,  0.01923311, ...,  0.00188601,
         0.00173163,  0.01030607],
       [-0.02312448,  0.5955038 ,  0.02102973, ...,  0.00146477,
         0.00158774,  0.0100581 ]], dtype=float32), 'smpl_scaling': array([93.77886], dtype=float32), 'smpl_trans': array([[-1.4792730e+01,  1.6935951e+02,  1.7916475e-01],
       [-1.4938223e+01,  1.6943605e+02,  1.6997068e-01],
       [-1.5107360e+01,  1.6954605e+02,  7.1443714e-02],
       ...,
       [ 5.0804868e+00,  1.7757001e+02,  4.8406234e+00],
       [ 5.1178832e

In [19]:
print(df['smpl_trans'])

[[-1.4792730e+01  1.6935951e+02  1.7916475e-01]
 [-1.4938223e+01  1.6943605e+02  1.6997068e-01]
 [-1.5107360e+01  1.6954605e+02  7.1443714e-02]
 ...
 [ 5.0804868e+00  1.7757001e+02  4.8406234e+00]
 [ 5.1178832e+00  1.7758218e+02  4.8407183e+00]
 [ 5.1210480e+00  1.7756790e+02  4.8775520e+00]]


In [20]:
print(len( df['smpl_trans']))

720


In [21]:
trans = df['smpl_trans']

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [23]:
from keras.preprocessing.sequence import TimeseriesGenerator

In [24]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [25]:
scaler.fit(trans) # fit the scaler object 
scaled_train = scaler.transform(trans)  # normalizing trans and storing into scaled_train 
print(scaled_train) # now data is in range of [0,1]
    

[[0.0181269  0.22609043 0.43029338]
 [0.01484054 0.23213768 0.43006286]
 [0.01102015 0.24082947 0.42759255]
 ...
 [0.46701658 0.87484264 0.54716796]
 [0.46786126 0.8758049  0.54717034]
 [0.46793276 0.8746767  0.54809386]]


In [46]:
 for i in range(720):
    
    train = [scaled_train[i][:2]]
    test = [scaled_train[i][2]]

    # print(train)
    # print(test)
    n_input = 1
    
    
    n_features = 1
    generator = TimeseriesGenerator(scaled_train , scaled_train , length = n_input , batch_size =1) #diving data into batches 
    
    x,y = generator[0]
#     print(f'given the array : \n{x.flatten()}')
#     print(f'predict this y: \n {y}')
    
    model = Sequential()
    model.add(LSTM(100,activation = 'relu' , input_shape=(n_input , n_features)))
    model.add(Dense(1))
    model.compile(optimizer='adam' , loss = 'mse')
    model.fit(generator, epochs = 50)
    loss_per_epoch = model.history.history['loss']
    plt.plot(range(len(loss_per_epoch)), loss_per_epoch)

    
   

Epoch 1/50


InvalidArgumentError: Graph execution error:

Detected at node 'sequential_2174/lstm_2174/while/lstm_cell_2174/MatMul' defined at (most recent call last):
    File "C:\Users\mpaks\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\mpaks\miniconda3\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\mpaks\miniconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
      app.start()
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 711, in start
      self.io_loop.start()
    File "C:\Users\mpaks\miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\mpaks\miniconda3\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "C:\Users\mpaks\miniconda3\lib\asyncio\base_events.py", line 1909, in _run_once
      handle._run()
    File "C:\Users\mpaks\miniconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "C:\Users\mpaks\miniconda3\lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
      result = self._run_cell(
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
      result = runner(coro)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\mpaks\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\mpaks\AppData\Local\Temp\ipykernel_4020\2113881905.py", line 22, in <module>
      model.fit(generator, epochs = 50)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 1050, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\training.py", line 558, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\sequential.py", line 412, in call
      return super().call(inputs, training=training, mask=mask)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\functional.py", line 512, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\functional.py", line 669, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\layers\rnn\base_rnn.py", line 556, in __call__
      return super().__call__(inputs, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\layers\rnn\lstm.py", line 625, in call
      last_output, outputs, states = backend.rnn(
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\backend.py", line 5169, in rnn
      final_outputs = tf.compat.v1.while_loop(
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\backend.py", line 5148, in _step
      output, new_states = step_function(
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\layers\rnn\lstm.py", line 623, in step
      return self.cell(inputs, states, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\layers\rnn\lstm.py", line 327, in call
      z = backend.dot(inputs, self.kernel)
    File "C:\Users\mpaks\miniconda3\lib\site-packages\keras\backend.py", line 2464, in dot
      out = tf.matmul(x, y)
Node: 'sequential_2174/lstm_2174/while/lstm_cell_2174/MatMul'
Matrix size-incompatible: In[0]: [1,3], In[1]: [1,400]
	 [[{{node sequential_2174/lstm_2174/while/lstm_cell_2174/MatMul}}]] [Op:__inference_train_function_526934]

In [ ]:
# from sklearn.preprocessing import StandardScaler
# import numpy as np

# # 4 samples/observations and 2 variables/features
# data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
# scaler = StandardScaler()
# scaled_data = scaler.fit_transform(data)

# print(data)

# print(scaled_data)
